name: CD

on:
  push:
    branches:
      - main
      - master
      - develop
      - feature/**
  pull_request:

jobs:
  publish-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish application
        run: dotnet publish Dima.Api/Dima.Api.csproj --configuration Release --output ./publish

      - name: Upload published artifact
        uses: actions/upload-artifact@v4
        with:
          name: dima-api-publish
          path: ./publish
